--01. Datos Operacionales (UNIACC.dbo)

SELECT
    -- CAMPOS VARCHAR NULLABLE - Requieren LTRIM/RTRIM + ISNULL
    CASE WHEN LTRIM(RTRIM(ISNULL(C.MAIL, ''))) = '' THEN NULL ELSE C.MAIL END AS MAIL_PERSONAL,
    CASE WHEN LTRIM(RTRIM(ISNULL(C.MAIL_INST, ''))) = '' THEN NULL ELSE C.MAIL_INST END AS MAIL_INSTITUCIONAL,
    CASE WHEN LTRIM(RTRIM(ISNULL(C.FONOACT, ''))) = '' THEN NULL ELSE C.FONOACT END AS TELEFONO_ACTUAL,
    CASE WHEN LTRIM(RTRIM(ISNULL(C.FONOPROC, ''))) = '' THEN NULL ELSE C.FONOPROC END AS TELEFONO_PROCEDENCIA,

    -- CAMPO DATETIME NOT NULL - Solo necesita verificación por conversión
    CASE WHEN C.FECNAC IS NULL THEN NULL ELSE CONVERT(VARCHAR(10), C.FECNAC, 23) END AS FECHA_NACIMIENTO,

    -- CONCATENACIÓN de campos (CODAPOD nullable + DIG nullable)
    CASE WHEN LTRIM(RTRIM(ISNULL(C.CODAPOD, ''))) = '' OR LTRIM(RTRIM(ISNULL(O.DIG, ''))) = ''
         THEN NULL
         ELSE C.CODAPOD + '-' + O.DIG END AS RUT_APODERDERO,

    -- CONCATENACIÓN de nombres (todos NOT NULL pero pueden estar vacíos)
    CASE WHEN LTRIM(RTRIM(ISNULL(C.NOMBRE, ''))) = ''
              AND LTRIM(RTRIM(ISNULL(C.PATERNO, ''))) = ''
              AND LTRIM(RTRIM(ISNULL(C.MATERNO, ''))) = ''
         THEN NULL
         ELSE LTRIM(RTRIM(ISNULL(C.NOMBRE, '') + ' ' + ISNULL(C.PATERNO, '') + ' ' + ISNULL(C.MATERNO, ''))) END AS NOMBRE_ALUMNO,

    -- CAMPO VARCHAR NULLABLE
    CASE WHEN LTRIM(RTRIM(ISNULL(C.NOMBRESOCIAL, ''))) = '' THEN NULL ELSE C.NOMBRESOCIAL END AS NOMBRE_SOCIAL,

    -- CONCATENACIÓN CODCLI(NOT NULL) + DIG(NULLABLE)
    CASE WHEN LTRIM(RTRIM(ISNULL(C.DIG, ''))) = '' THEN NULL ELSE C.CODCLI + '-' + C.DIG END AS RUT_ALUMNO,

    -- CAMPO NOT NULL - Solo verificar si está vacío
    CASE WHEN LTRIM(RTRIM(ISNULL(A.CODCLI, ''))) = '' THEN NULL ELSE A.CODCLI END AS CODCLI,

    -- NUEVO CAMPO: NIVEL DEL ALUMNO (lógica inline temporal)
    CASE WHEN LTRIM(RTRIM(ISNULL(A.CODCLI, ''))) = '' THEN NULL
         ELSE (
             -- Primero intenta obtener el nivel más bajo pendiente
             SELECT ISNULL(
                 (SELECT MIN(CONVERT(INT, COALESCE(c.nivel,0)))
                  FROM UNIACC.dbo.ra_curric c
                  INNER JOIN UNIACC.dbo.mt_alumno a2 ON c.codpestud = a2.CODPESTUD
                  WHERE a2.codcli = A.CODCLI
                    AND c.codramo NOT IN (SELECT codramo FROM UNIACC.dbo.ra_nota WHERE codcli = A.CODCLI AND estado IN ('A', 'E', 'I'))
                    AND c.CLASERAMO = '2'),
                 -- Si no hay pendientes, busca el nivel máximo cursado
                 (SELECT MAX(CONVERT(INT, COALESCE(c.nivel,0)))
                  FROM UNIACC.dbo.ra_curric c
                  INNER JOIN UNIACC.dbo.mt_alumno a2 ON c.codpestud = a2.CODPESTUD
                  WHERE a2.codcli = A.CODCLI
                    AND c.codramo IN (SELECT codramo FROM UNIACC.dbo.ra_nota WHERE codcli = A.CODCLI AND estado IN ('A', 'E', 'I'))
                    AND c.CLASERAMO = '2')
             )
         )
    END AS NIVEL_ALUMNO,

    ING.ANO_INGRESO_INSTITUCION,

    -- CAMPO VARCHAR NULLABLE (nota como texto)
    CASE WHEN LTRIM(RTRIM(ISNULL(C.NOTAEM, ''))) = '' THEN NULL ELSE C.NOTAEM END AS NEM,

    -- CAMPO VARCHAR NOT NULL (año como texto)
    CASE WHEN LTRIM(RTRIM(ISNULL(C.ANOEEM, ''))) = '' THEN NULL ELSE C.ANOEEM END AS ANIO_EGRESO_EM,

    CASE WHEN LTRIM(RTRIM(ISNULL(T.DESCRIPCION, ''))) = '' THEN NULL ELSE T.DESCRIPCION END AS TIPO_CARRERA,
    CASE WHEN LTRIM(RTRIM(ISNULL(A.ESTACAD, ''))) = '' THEN NULL ELSE A.ESTACAD END AS ESTADO_ACADEMICO,

    -- CAMPO VARCHAR NOT NULL
    CASE WHEN LTRIM(RTRIM(ISNULL(C.SEXO, ''))) = '' THEN NULL ELSE C.SEXO END AS GENERO,

    -- CAMPO VARCHAR NULLABLE
    CASE WHEN LTRIM(RTRIM(ISNULL(C.DIRPROC, ''))) = '' THEN NULL ELSE C.DIRPROC END AS DIRECCION,

    -- CAMPO VARCHAR NOT NULL
    CASE WHEN LTRIM(RTRIM(ISNULL(C.COMUNA, ''))) = '' THEN NULL ELSE C.COMUNA END AS COMUNA,
    CASE WHEN LTRIM(RTRIM(ISNULL(C.CIUDADACT, ''))) = '' THEN NULL ELSE C.CIUDADACT END AS CIUDAD,
    CASE WHEN LTRIM(RTRIM(ISNULL(RE.DESCRIPCION, ''))) = '' THEN NULL ELSE RE.DESCRIPCION END AS REGION,
    CASE WHEN LTRIM(RTRIM(ISNULL(C.NACIONALIDAD, ''))) = '' THEN NULL ELSE C.NACIONALIDAD END AS NACIONALIDAD,
    CASE WHEN LTRIM(RTRIM(ISNULL(C.CODESTCIVIL, ''))) = '' THEN NULL ELSE C.CODESTCIVIL END AS ESTADO_CIVIL,

    -- CONCATENACIÓN de campos numéricos de MT_ALUMNO
    CASE WHEN A.ANO_MAT IS NULL OR A.PERIODO_MAT IS NULL
         THEN NULL
         ELSE CONVERT(VARCHAR(10), A.ANO_MAT) + '-' + CONVERT(VARCHAR(1), A.PERIODO_MAT) END AS ULTIMA_MATRICULA,
     CONVERT(VARCHAR(10), GETDATE(), 23) AS FECHA_CORTE

FROM UNIACC.dbo.MT_ALUMNO A
INNER JOIN UNIACC.dbo.MT_CLIENT C ON A.RUT = C.CODCLI
INNER JOIN UNIACC.dbo.MT_CARRER R ON A.CODCARPR = R.CODCARR
INNER JOIN UNIACC.dbo.MT_APODER O ON C.CODAPOD = O.CODAPOD
INNER JOIN UNIACC.dbo.MT_TIPOCARR T ON R.TIPOCARR = T.TIPOCARR
INNER JOIN UNIACC.dbo.MT_COMUNA CO ON CO.NOMCOMUNA = C.COMUNA
INNER JOIN UNIACC.dbo.MT_REGION RE ON RE.CODREGION=CO.CODREGION
    CROSS APPLY (
    SELECT TOP 1 X.ANO AS ANO_INGRESO_INSTITUCION
    FROM UNIACC.dbo.MT_ALUMNO X
    WHERE X.RUT = A.RUT
    ORDER BY X.ANO ASC
) AS ING
WHERE A.ESTACAD IN ('VIGENTE', 'ELIMINADO', 'SUSPENDIDO') AND T.TIPOCARR=1
  AND ING.ANO_INGRESO_INSTITUCION >= 2022;


