select ben.CODCLI,
       ben.ANIO_BEN AS ANIO_BENEFICIO,
       ben.PERIODO_BEN AS PERIODO_BENEFICIO,
       ben.CODBEN AS CODIGO_BENEFICIO,
       dim.DESC_BENEFICIO AS DESCRIPCION_BENEFICIO,
       ben.MONTO_BEN AS MONTO_BENEFICIO,
       dim.ORIGEN_BENEFICIO,
       dim.TIPO_BENEFICIO,
       dim.APLICA_EN,
       CASE
           WHEN BEN.ESTADO_BENEFICIO IN ('PROCESO', '5') THEN 'PROCESO'
           WHEN BEN.ESTADO_BENEFICIO IN ('POSTULADO', '6')  THEN 'POSTULADO'
           WHEN BEN.ESTADO_BENEFICIO IN ('APROBADO','2') THEN 'APROBADO'
           WHEN BEN.ESTADO_BENEFICIO IN ('ASIGNADO', '4') THEN 'ASIGNADO'
           ELSE 'RECHAZADO'
        END AS 'ESTADO_BENEFICIO',
        CONVERT(VARCHAR(10), GETDATE(), 23) AS FECHA_CORTE

from [DWH_DAI_Server].DWH_DAI.dbo.ft_beneficios ben
INNER JOIN [DWH_DAI_Server].DWH_DAI.dbo.dim_beneficios dim ON ben.CODBEN = dim.CODBEN
WHERE ben.ANIO_BEN >= 2022;

