select ben.CODCLI,
       ben.ANIO_BEN AS ANIO_BENEFICIO,
       ben.PERIODO_BEN AS PERIODO_BENEFICIO,
       ben.CODBEN AS CODIGO_BENEFICIO,
       dim.DESC_BENEFICIO AS DESCRIPCION_BENEFICIO,
       ben.MONTO_BEN AS MONTO_BENEFICIO,
       dim.ORIGEN_BENEFICIO,
       dim.TIPO_BENEFICIO,
       dim.APLICA_EN,
       CASE
           WHEN BEN.ESTADO_BENEFICIO IN ('PROCESO', '5') THEN 'PROCESO'
           WHEN BEN.ESTADO_BENEFICIO IN ('POSTULADO', '6')  THEN 'POSTULADO'
           WHEN BEN.ESTADO_BENEFICIO IN ('APROBADO','2') THEN 'APROBADO'
           WHEN BEN.ESTADO_BENEFICIO IN ('ASIGNADO', '4') THEN 'ASIGNADO'
           ELSE 'RECHAZADO'
        END AS 'ESTADO_BENEFICIO'
from [DWH_DAI_Server].DWH_DAI.dbo.ft_beneficios ben, [DWH_DAI_Server].DWH_DAI.dbo.dim_beneficios dim
where ben.CODBEN = dim.CODBEN
    and ben.ANIO_BEN > 2022;

