SELECT
    -- === INFORMACIÓN BÁSICA ===
    N.CODCLI,
    N.RUT,
    N.RAMO_ALUMNO AS NOMBRE_RAMO,
    N.CODRAMO_ALUMNO AS COD_RAMO,
    N.CODRAMO_PLANIFICADO AS COD_RAMO_ACTA,
    LTRIM(RTRIM(SUBSTRING(N.NOMBRE_ALUMNO,CHARINDEX(' ', N.NOMBRE_ALUMNO, CHARINDEX(' ', N.NOMBRE_ALUMNO) + 1) + 1,
            LEN(NOMBRE_ALUMNO)))) AS NOMBRES,
    LEFT(NOMBRE_ALUMNO, CHARINDEX(' ', NOMBRE_ALUMNO + ' ') - 1) AS PATERNO,
    -- Apellido materno (segunda palabra)
    LTRIM(RTRIM(
        SUBSTRING(
            NOMBRE_ALUMNO,
            CHARINDEX(' ', NOMBRE_ALUMNO) + 1,
            CHARINDEX(' ', NOMBRE_ALUMNO + ' ', CHARINDEX(' ', NOMBRE_ALUMNO) + 1) - CHARINDEX(' ', NOMBRE_ALUMNO) - 1
        )
    )) AS MATERNO,
    --Extrae el % de Asistencia
     CASE
        WHEN ISNULL(AST.TOTAL_CLASES, 0) = 0 THEN 0
        ELSE CAST(ROUND((ISNULL(AST.TOTAL_ASISTENCIA, 0) * 100.0 / AST.TOTAL_CLASES), 2) AS DECIMAL(5,2))
    END AS ASISTENCIA,
    -- === PROMEDIO PONDERADO DE PARCIALES (REDONDEADO A 2 DECIMALES) ===
    CASE
        WHEN (CASE WHEN N.N1 IS NOT NULL THEN ISNULL(P.PARCIAL_1,0) ELSE 0 END +
              CASE WHEN N.N2 IS NOT NULL THEN ISNULL(P.PARCIAL_2,0) ELSE 0 END +
              CASE WHEN N.N3 IS NOT NULL THEN ISNULL(P.PARCIAL_3,0) ELSE 0 END +
              CASE WHEN N.N4 IS NOT NULL THEN ISNULL(P.PARCIAL_4,0) ELSE 0 END +
              CASE WHEN N.N5 IS NOT NULL THEN ISNULL(P.PARCIAL_5,0) ELSE 0 END +
              CASE WHEN N.N6 IS NOT NULL THEN ISNULL(P.PARCIAL_6,0) ELSE 0 END +
              CASE WHEN N.N7 IS NOT NULL THEN ISNULL(P.PARCIAL_7,0) ELSE 0 END) > 0
        THEN
            CAST(ROUND(
                (CASE WHEN N.N1 IS NOT NULL THEN N.N1 * ISNULL(P.PARCIAL_1,0)/100.0 ELSE 0 END +
                 CASE WHEN N.N2 IS NOT NULL THEN N.N2 * ISNULL(P.PARCIAL_2,0)/100.0 ELSE 0 END +
                 CASE WHEN N.N3 IS NOT NULL THEN N.N3 * ISNULL(P.PARCIAL_3,0)/100.0 ELSE 0 END +
                 CASE WHEN N.N4 IS NOT NULL THEN N.N4 * ISNULL(P.PARCIAL_4,0)/100.0 ELSE 0 END +
                 CASE WHEN N.N5 IS NOT NULL THEN N.N5 * ISNULL(P.PARCIAL_5,0)/100.0 ELSE 0 END +
                 CASE WHEN N.N6 IS NOT NULL THEN N.N6 * ISNULL(P.PARCIAL_6,0)/100.0 ELSE 0 END +
                 CASE WHEN N.N7 IS NOT NULL THEN N.N7 * ISNULL(P.PARCIAL_7,0)/100.0 ELSE 0 END) /
                (CASE WHEN N.N1 IS NOT NULL THEN ISNULL(P.PARCIAL_1,0)/100.0 ELSE 0 END +
                 CASE WHEN N.N2 IS NOT NULL THEN ISNULL(P.PARCIAL_2,0)/100.0 ELSE 0 END +
                 CASE WHEN N.N3 IS NOT NULL THEN ISNULL(P.PARCIAL_3,0)/100.0 ELSE 0 END +
                 CASE WHEN N.N4 IS NOT NULL THEN ISNULL(P.PARCIAL_4,0)/100.0 ELSE 0 END +
                 CASE WHEN N.N5 IS NOT NULL THEN ISNULL(P.PARCIAL_5,0)/100.0 ELSE 0 END +
                 CASE WHEN N.N6 IS NOT NULL THEN ISNULL(P.PARCIAL_6,0)/100.0 ELSE 0 END +
                 CASE WHEN N.N7 IS NOT NULL THEN ISNULL(P.PARCIAL_7,0)/100.0 ELSE 0 END)
            , 2) AS DECIMAL(5,2))
        ELSE NULL
    END AS NOTA_PRESENTACION,
    N.NOTA_EX AS NOTA_EXAMEN,
    N.NOTA_FINAL AS NOTA_FINAL,
    CASE WHEN N.ESTADO = 'A' THEN 'I' WHEN N.ESTADO = 'R' THEN 'R' ELSE NULL END AS ESTADO,
    N.PERIODO as PERIODO,
    N.ANO as ANIO,
    N.ESTADO_ALUMNO,
    N.CARRERA_ALUMNO,
    N.SECCION,
    N.NOMBRE_PROFESOR,
    N.ID_SECCION,

    -- === DATOS DE NOTAS ===
    CASE WHEN N.N1 IS NOT NULL THEN N.N1 END AS NOTA_1,
    CASE WHEN N.N1 IS NOT NULL THEN P.PARCIAL_1 END AS PONDERACION_1,

    CASE WHEN N.N2 IS NOT NULL THEN N.N2 END AS NOTA_2,
    CASE WHEN N.N2 IS NOT NULL THEN P.PARCIAL_2 END AS PONDERACION_2,

    CASE WHEN N.N3 IS NOT NULL THEN N.N3 END AS NOTA_3,
    CASE WHEN N.N3 IS NOT NULL THEN P.PARCIAL_3 END AS PONDERACION_3,

    CASE WHEN N.N4 IS NOT NULL THEN N.N4 END AS NOTA_4,
    CASE WHEN N.N4 IS NOT NULL THEN P.PARCIAL_4 END AS PONDERACION_4,

    CASE WHEN N.N5 IS NOT NULL THEN N.N5 END AS NOTA_5,
    CASE WHEN N.N5 IS NOT NULL THEN P.PARCIAL_5 END AS PONDERACION_5,

    CASE WHEN N.N6 IS NOT NULL THEN N.N6 END AS NOTA_6,
    CASE WHEN N.N6 IS NOT NULL THEN P.PARCIAL_6 END AS PONDERACION_6,

    CASE WHEN N.N7 IS NOT NULL THEN N.N7 END AS NOTA_7,
    CASE WHEN N.N7 IS NOT NULL THEN P.PARCIAL_7 END AS PONDERACION_7,


    -- === NOTAS FINALES ===
    N.CANT_NOTAS AS CANTIDAD_NOTAS_RAMO,
    N.PORC_PRES AS PONDERACION_NOTAS_PARA_EXAMEN,
    N.PORC_EX AS PODERACION_NOTA_EXAMEN,

    -- === DATOS DE ASISTENCIA ===
    ISNULL(AST.TOTAL_CLASES, 0) AS TOTAL_CLASES,
    ISNULL(AST.TOTAL_ASISTENCIA, 0) AS TOTAL_ASISTENCIA,
    ISNULL(AST.TOTAL_JUSTIFICACIONES, 0) AS TOTAL_JUSTIFICACIONES,
    ISNULL(AST.TOTAL_INASISTENCIAS, 0) AS TOTAL_INASISTENCIAS,
-- === PORCENTAJES DE ASISTENCIA ===
    CASE
        WHEN ISNULL(AST.TOTAL_CLASES, 0) = 0 THEN 0
        ELSE CAST(ROUND((ISNULL(AST.TOTAL_INASISTENCIAS, 0) * 100.0 / AST.TOTAL_CLASES), 2) AS DECIMAL(5,2))
    END AS PORCENTAJE_INASISTENCIA,
    CASE
        WHEN ISNULL(AST.TOTAL_CLASES, 0) = 0 THEN 0
        ELSE CAST(ROUND((ISNULL(AST.TOTAL_JUSTIFICACIONES, 0) * 100.0 / AST.TOTAL_CLASES), 2) AS DECIMAL(5,2))
    END AS PORCENTAJE_JUSTIFICACIONES,

    -- === METADATA ===
    CONVERT(VARCHAR(10), GETDATE(), 23) AS FECHA_CORTE

FROM ConectorIntegracion.dbo.PR_NOTAS N

-- LEFT JOIN para ponderaciones
LEFT JOIN (
    SELECT
        A.ANO,
        A.PERIODO,
        B.CODRAMO,
        B.CODSECC,
        B.ID_SECCION,
        MAX(CASE WHEN A.LINEA = 1 THEN A.PORCENTAJE END) AS PARCIAL_1,
        MAX(CASE WHEN A.LINEA = 2 THEN A.PORCENTAJE END) AS PARCIAL_2,
        MAX(CASE WHEN A.LINEA = 3 THEN A.PORCENTAJE END) AS PARCIAL_3,
        MAX(CASE WHEN A.LINEA = 4 THEN A.PORCENTAJE END) AS PARCIAL_4,
        MAX(CASE WHEN A.LINEA = 5 THEN A.PORCENTAJE END) AS PARCIAL_5,
        MAX(CASE WHEN A.LINEA = 6 THEN A.PORCENTAJE END) AS PARCIAL_6,
        MAX(CASE WHEN A.LINEA = 7 THEN A.PORCENTAJE END) AS PARCIAL_7
    FROM UNIACC.DBO.ra_Acteval_Seccion_det A
    INNER JOIN UNIACC.DBO.RA_SECCIO B
        ON A.ANO = B.ANO
        AND A.PERIODO = B.PERIODO
        AND A.CodRamo = B.CODRAMO
        AND A.CodSecc = B.CODSECC
    WHERE A.ANO >= 2022
        AND A.ACTIVIDAD = 'PARCIALES'
    GROUP BY A.ANO, A.PERIODO, B.CODRAMO, B.CODSECC, B.ID_SECCION
) P ON N.ID_SECCION = P.ID_SECCION

-- LEFT JOIN para datos de asistencia
LEFT JOIN (
    SELECT
        X.CODCLI, X.ANO, X.PERIODO, X.RAMO, X.SECCION,
        COUNT(1) as TOTAL_CLASES,
        SUM(CASE WHEN X.ESTADO='P' THEN 1 ELSE 0 END) as TOTAL_ASISTENCIA,
        SUM(CASE WHEN X.ESTADO='J' THEN 1 ELSE 0 END) as TOTAL_JUSTIFICACIONES,
        SUM(CASE WHEN X.ESTADO='A' OR X.ESTADO IS NULL OR X.ESTADO='' THEN 1 ELSE 0 END) as TOTAL_INASISTENCIAS
    FROM UNIACC.DBO.RA_CONTROLASIST X
    INNER JOIN UNIACC.DBO.RA_SECCIO S2
        ON X.ANO = S2.ANO
        AND X.PERIODO = S2.PERIODO
        AND X.RAMO = S2.CODRAMO
        AND X.SECCION = S2.CODSECC
    WHERE X.ANO >= 2022
    GROUP BY X.CODCLI, X.ANO, X.PERIODO, X.RAMO, X.SECCION
) AST ON AST.CODCLI = N.CODCLI
    AND AST.ANO = N.ANO
    AND AST.PERIODO = N.PERIODO
    AND EXISTS (
        SELECT 1 FROM UNIACC.DBO.RA_SECCIO S3
        WHERE S3.ID_SECCION = N.ID_SECCION
        AND AST.RAMO = S3.CODRAMO
        AND AST.SECCION = S3.CODSECC
    )

WHERE N.ANO >= 2022
    AND N.ACT_EVALUACION = 'PARCIALES'

ORDER BY N.ANO, N.PERIODO, N.ID_SECCION, N.CODCLI, N.RUT ASC;