SELECT A.CODCLI,
       A.ANO ANIO_INGRESO_INSTITUCION,
       P.ANO AS ANIO_BENEFICIO,
       P.PERIODO PERIODO_BENEFICIO,
       P.CODBEN AS CODIGO_BENEFICIO,
       B.DESCRIPCION AS DESCRIPCION_BENEFICIO,
       ISNULL(CAST(P.MONTO AS INT), 0) AS MONTO_BENEFICIO,
       B.ORIGEN_BENEFICIO,
       CASE
       WHEN B.TIPO = 'BECA' THEN 'BECA'
       ELSE 'DESCUENTO'
       END AS TIPO_BENEFICIO,
       CASE
       WHEN B.APLICONCEPTO='M' THEN 'MATRICULA'
       WHEN B.APLICONCEPTO='A' THEN 'ARANCEL'
       END AS APLICA_EN,
       E.DESCRIPCION AS ESTADO_BENEFICIO,
       CONVERT(VARCHAR(10), GETDATE(), 23) AS FECHA_CORTE
FROM UNIACC.DBO.MT_POSBEN P
INNER JOIN UNIACC.DBO.MT_ALUMNO A
ON P.CODCLI=A.RUT
AND P.CODCARR=A.CODCARPR
INNER JOIN UNIACC.DBO.MT_BENEFICIO B
ON P.CODBEN=B.CODBEN
INNER JOIN UNIACC.DBO.MT_ESTBEN E
ON P.ESTADO=E.ESTADO

WHERE P.ANO>=2022  --50.167