
-- 1. Datos de matrícula por alumno
SELECT MAIL, MAIL_INST, TELEFONO_ACT, TELEFONO_PROC, RUT_APODER,
       NOMBRE_ALUMNO, RUT, CODCLI, ANO_INGRESO_INSTITUCION, TIPO_CARRERA
FROM [DWH_DAI_Server].UCONECTORES.dbo.PR_MATRICULA
WHERE ANO_INGRESO_INSTITUCION >= 2022
  AND TIPO_CARRERA = 'PREGRADO'
  AND ESTADO_ACADEMICO IN ('VIGENTE', 'ELIMINADO', 'SUSPENDIDO')
ORDER BY ANO_INGRESO_INSTITUCION DESC, CODCLI;

-- 2. Planes académicos por alumno
SELECT CODCLI, CODIGO_PLAN, COD_CARRERA, NOMBRE_CARRERA, TIPO_CARRERA, ANO_INGRESO_INSTITUCION
FROM [DWH_DAI_Server].UCONECTORES.dbo.PR_MATRICULA
WHERE ANO_INGRESO_INSTITUCION >= 2022
  AND TIPO_CARRERA = 'PREGRADO'
  AND ESTADO_ACADEMICO IN ('VIGENTE', 'ELIMINADO', 'SUSPENDIDO')
ORDER BY ANO_INGRESO_INSTITUCION DESC, CODCLI;

-- 3. Información de colegio de alumnos
SELECT DISTINCT
    a.RUT,
    a.DV,
    ISNULL(e.RBD_COLEGIO, '') as RBD_COLEGIO,
    ISNULL(e.DESC_COLEGIO, '') as DESC_COLEGIO,
    ISNULL(e.COMUNA, '') as COMUNA,
    ISNULL(e.RURAL, 0) as RURAL,
    ISNULL(e.ORI_RELIGIOSA, 0) as ORI_RELIGIOSA
FROM [DWH_DAI_Server].DWH_DAI.dbo.dim_alumno a
INNER JOIN [DWH_DAI_Server].DWH_DAI.dbo.dim_matricula b ON a.RUT = b.RUT
INNER JOIN [DWH_DAI_Server].DWH_DAI.dbo.dim_plan_academico c ON b.CODPLAN = c.LLAVE_MALLA
LEFT JOIN [DWH_DAI_Server].DWH_DAI.dbo.dim_colegio e ON a.RBD_COLEGIO = e.RBD_COLEGIO
WHERE c.NIVEL_GLOBAL = 'pregrado'
ORDER BY a.RUT;

-- 4. Ramo por alumno (corregir SLECT por SELECT)
SELECT
    CODCLI, RUT, NOMBRE_RAMO, COD_RAMO, COD_RAMO_ACTA,
    NOMBRES, PATERNO, MATERNO, ASISTENCIA,
    NOTA_PRESENTACION, NOTA_EXAMEN, NOTA_FINAL,
    ESTADO, PERIODO, ANO
FROM [DWH_DAI_Server].UCONECTORES.dbo.PR_ALUMNO_RAMO
WHERE ANO >= 2022
  AND NIVEL_GLOBAL = 'pregrado'
  AND CODCLI IS NOT NULL
  AND CODCLI IN (
      SELECT CODCLI FROM [DWH_DAI_Server].UCONECTORES.dbo.PR_MATRICULA
      WHERE ESTADO_ACADEMICO IN ('VIGENTE', 'ELIMINADO', 'SUSPENDIDO')
  )
ORDER BY ANO DESC, PERIODO DESC, CODCLI, COD_RAMO;

-- 5. Fechas de matrícula
SELECT
    CODCLI, ANO_INGRESO_INSTITUCION, ANO_COHORTE, MATRICULA, FECHA_MATRICULA
FROM [DWH_DAI_Server].UCONECTORES.dbo.PR_MATRICULA
WHERE ANO_INGRESO_INSTITUCION >= 2022
  AND TIPO_CARRERA = 'PREGRADO'
  AND ESTADO_ACADEMICO IN ('VIGENTE', 'ELIMINADO', 'SUSPENDIDO')
ORDER BY ANO_INGRESO_INSTITUCION DESC, CODCLI;

-- 6. Estado académico por periodo
SELECT b.ano, b.periodo, b.CODCLI, b.RUT, b.asig_inscritas,
       CASE WHEN a.CODCLI IS NULL THEN 'no egresa' ELSE 'egresa' END as marca_egreso,
       CASE WHEN C.CODCLI IS NULL THEN 'no suspende' ELSE 'suspende' END as marca_suspendido,
       CASE WHEN d.CODCLI IS NULL THEN 'no eliminado' ELSE 'eliminado' END as marca_eliminado
FROM (
    SELECT ano, periodo, CODCLI, RUT, COUNT(1) as asig_inscritas
    FROM [DWH_DAI_Server].UCONECTORES.dbo.PR_ALUMNO_RAMO
    WHERE ano  >= 2022
      AND NIVEL_GLOBAL = 'pregrado'
      AND CODCLI IS NOT NULL
      AND CODCLI IN (
          SELECT CODCLI FROM [DWH_DAI_Server].UCONECTORES.dbo.PR_MATRICULA
          WHERE ESTADO_ACADEMICO IN ('VIGENTE', 'ELIMINADO', 'SUSPENDIDO')
      )
    GROUP BY ano, periodo, CODCLI, RUT
) b
LEFT JOIN [DWH_DAI_Server].UCONECTORES.dbo.PR_EGRESO a ON a.CODCLI = b.CODCLI AND a.ANO = b.ano AND a.PERIODO = b.periodo
LEFT JOIN (
    SELECT codcli, ano, periodo, estacad,
           ROW_NUMBER() OVER(PARTITION BY codcli, ano, periodo ORDER BY fechareg DESC) as orden
    FROM [DWH_DAI_Server].UCONECTORES.dbo.PR_ESTADOS_ACADEMICOS
    WHERE estacad = 'SUSPENDIDO'
      AND ano >= 2022
) c ON c.CODCLI = b.CODCLI AND c.ano = b.ano AND c.periodo = b.periodo AND c.orden = 1
LEFT JOIN (
    SELECT codcli, ano, periodo, estacad,
           ROW_NUMBER() OVER(PARTITION BY codcli, ano, periodo ORDER BY fechareg DESC) as orden
    FROM [DWH_DAI_Server].UCONECTORES.dbo.PR_ESTADOS_ACADEMICOS
    WHERE estacad = 'ELIMINADO'
      AND ano >= 2022
) d ON d.CODCLI = b.CODCLI AND d.ano = b.ano AND d.periodo = b.periodo AND d.orden = 1
ORDER BY b.ano DESC, b.periodo DESC, b.CODCLI;

-- 7. Datos personales de alumnos
SELECT DISTINCT
    a.RUT,
    a.DV,
    a.GENERO,
    CASE WHEN a.REGION IN ('NULL', '', ' ') OR a.REGION IS NULL THEN NULL ELSE a.REGION END as REGION,
    CASE WHEN a.COMUNA IN ('NULL', '', ' ') OR a.COMUNA IS NULL THEN NULL ELSE a.COMUNA END as COMUNA,
    CASE WHEN a.NACIONALIDAD IN ('NULL', '', ' ') OR a.NACIONALIDAD IS NULL THEN NULL ELSE a.NACIONALIDAD END as NACIONALIDAD,
    CASE WHEN a.FECH_NAC IN ('NULL', '', ' ') OR a.FECH_NAC IS NULL THEN NULL ELSE a.FECH_NAC END as FECH_NAC
FROM [DWH_DAI_Server].DWH_DAI.dbo.dim_alumno a
INNER JOIN [DWH_DAI_Server].DWH_DAI.dbo.dim_matricula b ON a.RUT = b.RUT
INNER JOIN [DWH_DAI_Server].DWH_DAI.dbo.dim_plan_academico c ON b.CODPLAN = c.LLAVE_MALLA
WHERE c.NIVEL_GLOBAL = 'pregrado';

-- 8. Seguimiento académico
SELECT
    CODCLI,
    NOMBRE_CARRERA,
    CODIGO_PLAN,
    COD_CARRERA,
    JORNADA,
    MODALIDAD,
    'VIGENTE' AS ESTADO_ACADEMICO,
    ANO_INGRESO_INSTITUCION,
    TIPO_CARRERA,
    COALESCE(NULLIF(LTRIM(RTRIM(SITUACION)), ''), 'ALUMNO REGULAR') AS SITUACION,
    CASE
        WHEN ESTADO_ACADEMICO = 'VIGENTE' THEN 'AVANCE ACADEMICO'
        WHEN ESTADO_ACADEMICO IN ('ELIMINADO', 'SUSPENDIDO') THEN 'REINGRESO'
        ELSE 'SIN CLASIFICAR'
    END AS TIPO_SEGUIMIENTO
FROM [DWH_DAI_Server].UCONECTORES.dbo.PR_MATRICULA
WHERE ANO_INGRESO_INSTITUCION >= 2022
  AND TIPO_CARRERA = 'PREGRADO'
  AND ESTADO_ACADEMICO IN ('VIGENTE', 'ELIMINADO', 'SUSPENDIDO')
ORDER BY ANO_INGRESO_INSTITUCION DESC, CODCLI;

-- 9. Transferencias de alumnos
SELECT
    a.CODCLI,
    CASE WHEN b.CODCLI IS NULL THEN 'sin transferencia' ELSE 'con transferencia' END as transferencia,
    CASE WHEN b.cant IS NULL THEN 0 ELSE b.cant END as cantidad_transferido,
    a.ANO_INGRESO_INSTITUCION
FROM [DWH_DAI_Server].UCONECTORES.dbo.PR_MATRICULA a
LEFT JOIN (
    SELECT codcli, COUNT(1) as cant
    FROM [DWH_DAI_Server].UCONECTORES.dbo.PR_ALUMNO_RAMO
    WHERE CONCEPTO = 'cv'
    GROUP BY codcli
) b ON a.CODCLI = b.CODCLI
WHERE a.ANO_INGRESO_INSTITUCION >= 2022
  AND a.TIPO_CARRERA = 'PREGRADO'
  AND a.ESTADO_ACADEMICO IN ('VIGENTE', 'ELIMINADO', 'SUSPENDIDO')
ORDER BY a.ANO_INGRESO_INSTITUCION DESC, a.CODCLI;

-- 10. Reporte de finanzas
SELECT
    CODCLI, NOMBRE_CARRERA, NOMBRE_AREA, MODALIDAD, PERIODO, RUT, NOMBRE_ALUMNO,
    RUT_APODER, NOMBRE_APODERADO, MAT_PRIMER_AÑO, MONTO_MATRICULA, MONTO_ARANCEL,
    CUOTA_MATRICULA, CUOTA_ARANCEL, DESC_MATRICULA, DESC_ARANCEL, BECA_MATRICULA,
    BECA_ARANCEL, VALOR_TOTAL_MATRICULA, VALOR_TOTAL_ARANCEL, PAGOS_POR_MORA,
    CUOTAS_MATRICULA_VENCIDAS, MONTO_MATRICULA_VENCIDAS, MONTO_ARANCEL_VENCIDAS,
    MONTO_MATRICULA_POR_VENCER, MONTO_ARANCEL_POR_VENCER
FROM [DWH_DAI_Server].UCONECTORES.dbo.REP_REPORTE_FINANZAS
ORDER BY PERIODO DESC;