--01. Datos Operacionales
SELECT
    C.MAIL AS MAIL_PERSONAL,
    C.MAIL_INST AS MAIL_INSTITUCIONAL,
    C.FONOACT AS TELEFONO_ACT,
    C.FONOPROC AS TELEFONO_PROC,
    CONVERT(VARCHAR(10), C.FECNAC, 23) AS FECHA_NACIMIENTO,
    C.CODAPOD + '-' + O.DIG AS RUT_APODERDERO,
    C.NOMBRE + ' ' + C.PATERNO + ' ' + C.MATERNO AS NOMBRE_ALUMNO,
    C.NOMBRESOCIAL AS NOMBRE_SOCIAL,
    C.CODCLI + '-' + C.DIG AS RUT_ALUMNO,
    A.CODCLI,
    ING.ANO_INGRESO_INSTITUCION,
    C.NOTAEM AS NEM,
    C.ANOEEM AS FECHA_NEM,
    T.DESCRIPCION AS TIPO_CARRERA,
    A.ESTACAD AS ESTADO_ACADEMICO,
    C.SEXO AS GENERO,
    C.DIRPROC AS DIRECCION,
    C.COMUNA,
    C.CIUDADACT AS CIUDAD,
	RE.DESCRIPCION AS REGION,
    C.NACIONALIDAD AS NACIONALIDAD,
    C.CODESTCIVIL AS ESTADO_CIVIL,
    CONVERT(VARCHAR(10), A.ANO_MAT) + '-' + CONVERT(VARCHAR(1), A.PERIODO_MAT) AS ULTIMA_MATRICULA
FROM MT_ALUMNO A
INNER JOIN MT_CLIENT C ON A.RUT = C.CODCLI
INNER JOIN MT_CARRER R ON A.CODCARPR = R.CODCARR
INNER JOIN MT_APODER O ON C.CODAPOD = O.CODAPOD
INNER JOIN MT_TIPOCARR T ON R.TIPOCARR = T.TIPOCARR
INNER JOIN MT_COMUNA CO ON CO.NOMCOMUNA = C.COMUNA
INNER JOIN MT_REGION RE ON RE.CODREGION=CO.CODREGION
    CROSS APPLY (
    SELECT TOP 1 X.ANO AS ANO_INGRESO_INSTITUCION
    FROM MT_ALUMNO X
    WHERE X.RUT = A.RUT
    ORDER BY X.ANO ASC
) AS ING
WHERE A.ESTACAD IN ('VIGENTE', 'ELIMINADO', 'SUSPENDIDO') AND T.TIPOCARR=1
  AND ING.ANO_INGRESO_INSTITUCION >= 2022;--8936


--02. Encuestas docentes
select NOMBRE_ENCUESTA, ANO as anio, PERIODO, NRO_PREGUNTA, PREGUNTA, CODRAMO, NOMBRE_RAMO, SECCION_RAMO, CODCARR, NOMBRE_CARRERA, RUT_DOCENTE, NOMBRE_DOCENTE, CODCLI, NOMBRE_USUARIO, CODRESPUESTA, ID_RESP, RESPUESTA, OPCION, TEXTOLIBRE, OBSERVACION, JORNADA, MODALIDAD, NIVEL_GLOBAL, current_timestamp as fecha_corte
from PR_ENCUESTAS where NIVEL_GLOBAL = 'PREGRADO';



--SELECT * FROM MT_REGION