--01. Datos Operacionales
SELECT
    C.MAIL,
    C.MAIL_INST,
    C.FONOACT AS TELEFONO_ACT,
    C.FONOPROC AS TELEFONO_PROC,
    CONVERT(VARCHAR(10), C.FECNAC, 23) AS FECNAC,
    C.CODAPOD + '-' + O.DIG AS RUT_APODER,
    C.NOMBRE + ' ' + C.PATERNO + ' ' + C.MATERNO AS NOMBRE_ALUMNO,
    C.NOMBRESOCIAL,
    C.CODCLI + '-' + C.DIG AS RUT,
    A.CODCLI,
    ING.ANO_INGRESO_INSTITUCION,
    C.NOTAEM,
    C.ANOEEM,
    T.DESCRIPCION AS TIPO_CARRERA,
    A.ESTACAD AS ESTADO_ACADEMICO,
    C.SEXO AS GENERO,
    C.REGION,
    C.COMUNA,
    C.CIUDADACT,
    C.NACIONALIDAD,
    C.CODESTCIVIL,
    CONVERT(VARCHAR(10), A.ANO_MAT) + '-' + CONVERT(VARCHAR(1), A.PERIODO_MAT) AS ULTIMA_MATRICULA
FROM MT_ALUMNO A
INNER JOIN MT_CLIENT C ON A.RUT = C.CODCLI
INNER JOIN MT_CARRER R ON A.CODCARPR = R.CODCARR
INNER JOIN MT_APODER O ON C.CODAPOD = O.CODAPOD
INNER JOIN MT_TIPOCARR T ON R.TIPOCARR = T.TIPOCARR
CROSS APPLY (
    SELECT TOP 1 X.ANO AS ANO_INGRESO_INSTITUCION
    FROM MT_ALUMNO X
    WHERE X.RUT = A.RUT
    ORDER BY X.ANO ASC
) AS ING
WHERE A.ESTACAD IN ('VIGENTE', 'ELIMINADO', 'SUSPENDIDO') AND T.TIPOCARR=1
  AND ING.ANO_INGRESO_INSTITUCION >= 2022;


select * from MT_CLIENT