select cod_incidencia,
       cod_alurut,
       cod_carrera,
       des_carrera,
       codcli,
       des_consejero,
       des_estado,
       des_incidencia,
       des_categoria,
       des_subcategoria,
       des_login_ingreso,
       des_login_asignado,
       des_login_derivado,
       fec_ingreso,
       fec_ultmod,
       nro_minuto_total,
       nro_minuto_etapa,
       nro_minuto_vencido,
       cod_grupo_incidencia,
       des_observacion,
       des_respuesta,
       des_grupo,
       des_anulacion,
       bool_portal,
       cod_escuela,
       des_escuela,
       bool_nuevo, asignado_login, asignado_nombre, alumno_nombre, alumno_apepri, alumno_apeseg, alumno_email, alumno_telefono, alumno_celular
from "10_solicitudes_crm"
where cod_categoria = 16 and cod_subcategoria in (191, 192, 195, 196, 197, 200, 208, 209, 210, 211, 212)