--Versión 2.1
WITH EstadosAcademicos AS (
    SELECT
        rut as RUT,
        ano as ANIO,
        estacad as ESTADO_ACADEMICO,
        CONVERT(char(8), fechareg, 112) as FECHA_REGISTRO_ESTADO_ACADEMICO,
        ROW_NUMBER() OVER(partition by rut, ano order by fechareg desc) as ORDEN
    FROM [DWH_DAI_Server].UConectores.dbo.PR_ESTADOS_ACADEMICOS
    WHERE tipo_carrera = 'pregrado'
      AND ano >= 2022
),
EstadosPorAnio AS (
    SELECT
        RUT,
        MAX(CASE WHEN ANIO = 2022 THEN ESTADO_ACADEMICO END) AS ESTADO_ACADEMICO_2022,
        MAX(CASE WHEN ANIO = 2022 THEN FECHA_REGISTRO_ESTADO_ACADEMICO END) AS FECHA_REGISTRO_2022,
        MAX(CASE WHEN ANIO = 2023 THEN ESTADO_ACADEMICO END) AS ESTADO_ACADEMICO_2023,
        MAX(CASE WHEN ANIO = 2023 THEN FECHA_REGISTRO_ESTADO_ACADEMICO END) AS FECHA_REGISTRO_2023,
        MAX(CASE WHEN ANIO = 2024 THEN ESTADO_ACADEMICO END) AS ESTADO_ACADEMICO_2024,
        MAX(CASE WHEN ANIO = 2024 THEN FECHA_REGISTRO_ESTADO_ACADEMICO END) AS FECHA_REGISTRO_2024,
        MAX(CASE WHEN ANIO = 2025 THEN ESTADO_ACADEMICO END) AS ESTADO_ACADEMICO_2025,
        MAX(CASE WHEN ANIO = 2025 THEN FECHA_REGISTRO_ESTADO_ACADEMICO END) AS FECHA_REGISTRO_2025
    FROM EstadosAcademicos
    WHERE ORDEN = 1
    GROUP BY RUT
)

SELECT
    -- CAMPOS SOLICITADOS PRIMERO
    CASE WHEN LTRIM(RTRIM(ISNULL(C.MAIL, ''))) = '' THEN NULL ELSE C.MAIL END AS MAIL,
    CASE WHEN LTRIM(RTRIM(ISNULL(C.MAIL_INST, ''))) = '' THEN NULL ELSE C.MAIL_INST END AS MAIL_INST,
    CASE WHEN LTRIM(RTRIM(ISNULL(C.FONOACT, ''))) = '' THEN NULL ELSE C.FONOACT END AS TELEFONO_ACT,
    CASE WHEN LTRIM(RTRIM(ISNULL(C.FONOPROC, ''))) = '' THEN NULL ELSE C.FONOPROC END AS TELEFONO_PROC,
    CASE WHEN LTRIM(RTRIM(ISNULL(C.CODAPOD, ''))) = '' OR LTRIM(RTRIM(ISNULL(O.DIG, ''))) = ''
         THEN NULL
         ELSE C.CODAPOD + '-' + O.DIG END AS RUT_APODER,
    CASE WHEN LTRIM(RTRIM(ISNULL(C.NOMBRE, ''))) = ''
              AND LTRIM(RTRIM(ISNULL(C.PATERNO, ''))) = ''
              AND LTRIM(RTRIM(ISNULL(C.MATERNO, ''))) = ''
         THEN NULL
         ELSE LTRIM(RTRIM(ISNULL(C.NOMBRE, '') + ' ' + ISNULL(C.PATERNO, '') + ' ' + ISNULL(C.MATERNO, ''))) END AS NOMBRE_ALUMNO,
    CASE WHEN LTRIM(RTRIM(ISNULL(C.DIG, ''))) = '' THEN NULL ELSE C.CODCLI + '-' + C.DIG END AS RUT,
    CASE WHEN LTRIM(RTRIM(ISNULL(A.CODCLI, ''))) = '' THEN NULL ELSE A.CODCLI END AS CODCLI,
    ING.ANO_INGRESO_INSTITUCION,
    CASE WHEN LTRIM(RTRIM(ISNULL(T.DESCRIPCION, ''))) = '' THEN NULL ELSE T.DESCRIPCION END AS TIPO_CARRERA,

    -- RESTO DE CAMPOS DE LA QUERY ORIGINAL
    CASE WHEN LTRIM(RTRIM(ISNULL(C.NOMBRESOCIAL, ''))) = '' THEN NULL ELSE C.NOMBRESOCIAL END AS NOMBRE_SOCIAL,
    CASE WHEN C.FECNAC IS NULL THEN NULL ELSE CONVERT(VARCHAR(10), C.FECNAC, 23) END AS FECHA_NACIMIENTO,
    F.DESCRIPCION AS NOMBRE_FACULTAD,
    U.NOMBRE AS NOMBRE_ESCUELA,
    R.CODCARR AS COD_CARRERA,
    R.NOMBRE_L AS NOMBRE_CARRERA,
    A.CODPESTUD AS CODIGO_PLAN,
    P.NOMPESTUD AS NOMBRE_PLAN,
    (SELECT MAX(CAST(X.NIVEL AS INT)) FROM UNIACC.DBO.RA_CURRIC X WHERE X.CODPESTUD=A.CODPESTUD AND X.CODRAMO NOT IN ('PREX1010','DEEX1010')) DURACION,
    A.JORNADA,
    UNIACC.DBO.fn_Obtiene_Nivel_alumno(A.CODCLI) AS NIVEL_ALUMNO,
    CASE WHEN LTRIM(RTRIM(ISNULL(C.NOTAEM, ''))) = '' THEN NULL ELSE C.NOTAEM END AS NEM,
    CASE WHEN LTRIM(RTRIM(ISNULL(C.ANOEEM, ''))) = '' THEN NULL ELSE C.ANOEEM END AS ANO_EGRESO_EM,
    (SELECT TOP 1 X.PAAVERBAL FROM UNIACC.DBO.MT_PAA X WHERE X.CODCLI=A.RUT ORDER BY X.FECMOD DESC) PAAVERBAL,
    (SELECT TOP 1 X.PAAMATEMAT FROM UNIACC.DBO.MT_PAA X WHERE X.CODCLI=A.RUT ORDER BY X.FECMOD DESC) PAAMATEMAT,
    (SELECT TOP 1 X.PAAHISGEO FROM UNIACC.DBO.MT_PAA X WHERE X.CODCLI=A.RUT ORDER BY X.FECMOD DESC) PAAHISGEO,
    (SELECT TOP 1 X.PSUVERVAL FROM UNIACC.DBO.MT_PAA X WHERE X.CODCLI=A.RUT ORDER BY X.FECMOD DESC) PSUVERBAL,
    (SELECT TOP 1 X.PSUMATEMAT FROM UNIACC.DBO.MT_PAA X WHERE X.CODCLI=A.RUT ORDER BY X.FECMOD DESC) PSUMATEMAT,
    (SELECT TOP 1 X.PSUHISGEO FROM UNIACC.DBO.MT_PAA X WHERE X.CODCLI=A.RUT ORDER BY X.FECMOD DESC) PSUHISGEO,
    (SELECT TOP 1 X.TIPOPRUEBA FROM UNIACC.DBO.MT_PAA X WHERE X.CODCLI=A.RUT ORDER BY X.FECMOD DESC) TIPOPRUEBA,
    (SELECT TOP 1 X.PROMEDIOPSU FROM UNIACC.DBO.MT_PAA X WHERE X.CODCLI=A.RUT ORDER BY X.FECMOD DESC) PROM_PRUEBA,
    CASE WHEN LTRIM(RTRIM(ISNULL(A.ESTACAD, ''))) = '' THEN NULL ELSE A.ESTACAD END AS ESTADO_ACADEMICO,
    CASE WHEN LTRIM(RTRIM(ISNULL(C.SEXO, ''))) = '' THEN NULL ELSE C.SEXO END AS GENERO,
    CASE WHEN LTRIM(RTRIM(ISNULL(C.DIRPROC, ''))) = '' THEN NULL ELSE C.DIRPROC END AS DIRECCION,
    CASE WHEN LTRIM(RTRIM(ISNULL(C.COMUNA, ''))) = '' THEN NULL ELSE C.COMUNA END AS COMUNA,
    CASE WHEN LTRIM(RTRIM(ISNULL(C.CIUDADACT, ''))) = '' THEN NULL ELSE C.CIUDADACT END AS CIUDAD,
    CASE WHEN LTRIM(RTRIM(ISNULL(RE.DESCRIPCION, ''))) = '' THEN NULL ELSE RE.DESCRIPCION END AS REGION,
    CASE WHEN LTRIM(RTRIM(ISNULL(C.NACIONALIDAD, ''))) = '' THEN NULL ELSE C.NACIONALIDAD END AS NACIONALIDAD,
    CASE WHEN LTRIM(RTRIM(ISNULL(C.CODESTCIVIL, ''))) = '' THEN NULL ELSE C.CODESTCIVIL END AS ESTADO_CIVIL,
    CASE WHEN A.ANO_MAT IS NULL OR A.PERIODO_MAT IS NULL
         THEN NULL
         ELSE CONVERT(VARCHAR(10), A.ANO_MAT) + '-' + CONVERT(VARCHAR(1), A.PERIODO_MAT) END AS ULTIMA_MATRICULA,
    EST.ESTADO_ACADEMICO_2022,
    EST.FECHA_REGISTRO_2022,
    EST.ESTADO_ACADEMICO_2023,
    EST.FECHA_REGISTRO_2023,
    EST.ESTADO_ACADEMICO_2024,
    EST.FECHA_REGISTRO_2024,
    EST.ESTADO_ACADEMICO_2025,
    EST.FECHA_REGISTRO_2025,
    CONVERT(VARCHAR(10), GETDATE(), 23) AS FECHA_CORTE

FROM UNIACC.dbo.MT_ALUMNO A
INNER JOIN UNIACC.dbo.MT_CLIENT C ON A.RUT = C.CODCLI
INNER JOIN UNIACC.dbo.MT_CARRER R ON A.CODCARPR = R.CODCARR
INNER JOIN UNIACC.dbo.MT_APODER O ON C.CODAPOD = O.CODAPOD
INNER JOIN UNIACC.dbo.MT_TIPOCARR T ON R.TIPOCARR = T.TIPOCARR
INNER JOIN UNIACC.dbo.MT_COMUNA CO ON CO.NOMCOMUNA = C.COMUNA
INNER JOIN UNIACC.dbo.MT_REGION RE ON RE.CODREGION = CO.CODREGION
LEFT JOIN UNIACC.DBO.RA_FACULTAD F ON F.CODFAC = R.CODFAC
LEFT JOIN UNIACC.DBO.RA_UNACAD U ON U.CODUACAD = R.CODUACAD
LEFT JOIN UNIACC.DBO.RA_PESTUD P ON P.CODPESTUD = A.CODPESTUD
LEFT JOIN EstadosPorAnio EST ON
    CASE WHEN LTRIM(RTRIM(ISNULL(C.DIG, ''))) = '' THEN NULL
         ELSE C.CODCLI + '-' + C.DIG END = EST.RUT
CROSS APPLY (
    SELECT TOP 1 X.ANO AS ANO_INGRESO_INSTITUCION
    FROM UNIACC.dbo.MT_ALUMNO X
    WHERE X.RUT = A.RUT
    ORDER BY X.ANO ASC
) AS ING

WHERE A.ESTACAD IN ('VIGENTE', 'ELIMINADO', 'SUSPENDIDO') AND T.TIPOCARR = 1
  AND ING.ANO_INGRESO_INSTITUCION >= 2022;