SELECT DISTINCT
    UPPER(a.NOMBRE_CARRERA) AS NOMBRE_CARRERA,
    UPPER(a.TIPO_PLAN_CARRERA) AS TIPO_PLAN_CARRERA,
    UPPER(a.NOMBRE_TITULO) AS NOMBRE_TITULO,
    UPPER(a.NOMBRE_GRADO) AS NOMBRE_GRADO,
    UPPER(a.NIVEL_GLOBAL) AS NIVEL_GLOBAL,
    UPPER(a.AREA_ACTUAL) AS AREA_ACTUAL,
    UPPER(a.vigencia) AS VIGENCIA,
    UPPER(e.DESC_ESCUELA) AS DESCRIPCION_ESCUELA,
    UPPER(f.DESC_FACULTAD) AS DESCRIPCION_FACULTAD
FROM DWH_DAI.dbo.dim_plan_academico a
INNER JOIN UConectores.dbo.pr_matricula b ON a.LLAVE_MALLA = b.CODIGO_PLAN
INNER JOIN DWH_DAI.dbo.dim_escuela e ON a.ID_ESCUELA = e.ID_ESCUELA
INNER JOIN DWH_DAI.dbo.dim_facultades f ON e.ID_FACULTAD = f.ID_FACULTAD
WHERE a.NIVEL_GLOBAL = 'pregrado'
    --AND a.vigencia = 'SI'
    AND a.TIPO_PLAN_CARRERA = 'Plan Regular'
ORDER BY UPPER(f.DESC_FACULTAD), UPPER(e.DESC_ESCUELA), UPPER(a.NOMBRE_CARRERA);