SELECT DISTINCT
    A.ANO ANO_INGRESO,
    A.PERIODO PERIODO_INGR,
    A.ANO_MAT,
    A.PERIODO_MAT,
    (CONVERT(VARCHAR(10), G.ANO) + '-' + CONVERT(VARCHAR(10), G.PERIODO)) MAT_EFECTIVA,
    CONVERT(VARCHAR(10), A.FEC_MAT, 103) FEC_MAT,
    (
        SELECT TOP 1
            CONVERT(VARCHAR(8), X.FECMOD, 108)  -- HH:mm:ss
        FROM UNIACC.DBO.MT_CTADOC X
        WHERE X.CODCLI = A.RUT
          AND X.CODCARR = A.CODCARPR
          AND X.ITEM = 2
          AND X.ANO = 2026
    ) HORA_MAT,
    A.CODCLI,
    A.RUT,
    B.DIG,
    B.NOMBRE,
    B.PATERNO APELLIDO_PAT,
    B.MATERNO APELLIDO_MAT,
    A.CODCARPR,
    C.NOMBRE_C CARRERA,
    A.CODPESTUD,
    UNIACC.DBO.fn_Obtiene_Nivel_alumno(A.CODCLI) NIVEL,
    A.JORNADA,
    D.DESCRIPCION TIPO_CARR,
    E.DESCRIPCION FACULTAD,
    A.ESTACAD,
    A.TIPOSITU,
    F.DESCRIPCION DESCRIPCION_SITU,
    CASE
        WHEN A.ANO = 2026 THEN 'NUEVO'
        WHEN A.ANO < 2026 THEN 'ANTIGUO'
    END TIPO_ALUMNO,
    U.DESCRIPCION CATEGORIA,
    (SELECT TOP 1 X.MONTO
     FROM UNIACC.DBO.MT_DOCITEM X
     WHERE X.CODCLI = A.RUT AND X.CODCARR = A.CODCARPR AND X.ANO = 2026 AND X.ITEM = 1) LISTA_MAT,
    (SELECT SUM(Z.MONTO)
     FROM UNIACC.DBO.MT_CTADOC X, UNIACC.DBO.MT_CTADEP Z
     WHERE X.CODCLI = A.RUT AND X.CODCARR = A.CODCARPR
       AND X.CODCLI = Z.CODCLI AND X.CODCARR = Z.CODCARR
       AND X.ITEM = 1
       AND X.CTADOCNUM = Z.CTADOCNUM AND X.CTADOC = Z.CTADOC
       AND Z.CTAPAG = 373
       AND X.ANO = Z.ANO AND Z.ANO = 2026) BEN_MATR,
    (SELECT SUM(Y.MONTO)
     FROM UNIACC.DBO.MT_CTADOC X, UNIACC.DBO.MT_CTADEP Y
     WHERE X.CODCLI = A.RUT AND X.CODCARR = A.CODCARPR
       AND X.CODCLI = Y.CODCLI AND X.CODCARR = Y.CODCARR
       AND X.CTADOC = Y.CTADOC AND X.CTADOCNUM = Y.CTADOCNUM
       AND X.NUM_OPERACION = Y.NUM_OPERACION
       AND X.ITEM = 1
       AND Y.CTAPAG <> 373
       AND X.ANO = 2026) COPAGO_MAT,
    (SELECT TOP 1 Z.NOMBRE
     FROM UNIACC.DBO.MT_CTADOC X, UNIACC.DBO.MT_CTADEP Y, UNIACC.DBO.MT_DOCPAG Z
     WHERE X.CODCLI = A.RUT AND X.CODCARR = A.CODCARPR
       AND X.CODCLI = Y.CODCLI AND X.CODCARR = Y.CODCARR
       AND X.CTADOC = Y.CTADOC AND X.CTADOCNUM = Y.CTADOCNUM
       AND Y.CTAPAG = Z.TIPODOC
       AND X.NUM_OPERACION = Y.NUM_OPERACION
       AND X.ITEM = 1
       AND Y.CTAPAG <> 373
       AND X.ANO = 2026) DOCUMENTO_MAT,
    (SELECT TOP 1 X.MONTO
     FROM UNIACC.DBO.MT_DOCITEM X
     WHERE X.CODCLI = A.RUT AND X.CODCARR = A.CODCARPR AND X.ANO = 2026 AND X.ITEM = 2) LISTA_ARANCEL,
    (SELECT SUM(Z.MONTO)
     FROM UNIACC.DBO.MT_CTADOC X, UNIACC.DBO.MT_CTADEP Z
     WHERE X.CODCLI = A.RUT AND X.CODCARR = A.CODCARPR
       AND X.CODCLI = Z.CODCLI AND X.CODCARR = Z.CODCARR
       AND X.ITEM = 2
       AND X.CTADOCNUM = Z.CTADOCNUM AND X.CTADOC = Z.CTADOC
       AND Z.CTAPAG IN (373, 20, 374, 375)
       AND X.ANO = Z.ANO AND Z.ANO = 2026) BEN_ARAN,
    (SELECT SUM(Y.MONTO)
     FROM UNIACC.DBO.MT_CTADOC X, UNIACC.DBO.MT_CTADEP Y
     WHERE X.CODCLI = A.RUT AND X.CODCARR = A.CODCARPR
       AND X.CODCLI = Y.CODCLI AND X.CODCARR = Y.CODCARR
       AND X.CTADOC = Y.CTADOC AND X.CTADOCNUM = Y.CTADOCNUM
       AND X.NUM_OPERACION = Y.NUM_OPERACION
       AND X.ITEM = 2
       AND Y.CTAPAG NOT IN (373, 20, 374, 375)
       AND X.ANO = 2026) COPAGO_ARA,
    (SELECT TOP 1 Z.NOMBRE
     FROM UNIACC.DBO.MT_CTADOC X, UNIACC.DBO.MT_CTADEP Y, UNIACC.DBO.MT_DOCPAG Z
     WHERE X.CODCLI = A.RUT AND X.CODCARR = A.CODCARPR
       AND X.CODCLI = Y.CODCLI AND X.CODCARR = Y.CODCARR
       AND X.CTADOC = Y.CTADOC AND X.CTADOCNUM = Y.CTADOCNUM
       AND Y.CTAPAG = Z.TIPODOC
       AND X.NUM_OPERACION = Y.NUM_OPERACION
       AND X.ITEM = 2
       AND Y.CTAPAG NOT IN (373, 20, 374, 375)
       AND X.ANO = 2026) DOCUMENTO_ARA,
    (SELECT SUM(Z.MONTO)
     FROM UNIACC.DBO.MT_CTADOC X, UNIACC.DBO.MT_CTADEP Z
     WHERE X.CODCLI = A.RUT AND X.CODCARR = A.CODCARPR
       AND X.CODCLI = Z.CODCLI AND X.CODCARR = Z.CODCARR
       AND X.CTADOC = Z.CTADOC
       AND X.CTADOCNUM = Z.CTADOCNUM AND X.NUM_OPERACION = Z.NUM_OPERACION
       AND X.ITEM IN (1, 2)
       AND Z.CTAPAG NOT IN (20, 373, 374, 375)
       AND X.ANO = 2026) COPAGO_TOTAL,
    (SELECT SUM(X.MONTO)
     FROM UNIACC.DBO.MT_CTADOC X
     WHERE X.CODCLI = A.RUT AND X.CODCARR = A.CODCARPR AND X.ANO = 2026 AND X.CTADOC = 21) CAE_MONTO,
    (SELECT TOP 1
        CASE
            WHEN X.SALDO > 0 AND X.FECVEN >= GETDATE() THEN 'VIGENTE'
            WHEN X.SALDO = 0 THEN 'CANCELADA'
            WHEN X.SALDO > 0 AND X.FECVEN < GETDATE() THEN 'MOROSO'
        END
     FROM UNIACC.DBO.MT_CTADOC X
     WHERE X.CODCLI = A.RUT AND X.CODCARR = A.CODCARPR AND X.ANO = 2026 AND X.CTADOC = 21) ESTADO_CAE,
    (SELECT TOP 1 Z.DESCRIPCION
     FROM UNIACC.DBO.MT_POSBEN X, UNIACC.DBO.MT_BENEFICIO Z
     WHERE X.CODBEN = Z.CODBEN
       AND Z.ORIGEN_BENEFICIO = 'EXTERNO'
       AND X.ESTADO = 4
       AND X.CODCLI = A.RUT
       AND X.CODCARR = A.CODCARPR
       AND X.ANO = 2026
       AND X.CODBEN <> 4) BECA_MINISTERIAL,
    (SELECT SUM(X.MONTO)
     FROM UNIACC.DBO.MT_CTADOC X
     WHERE X.CODCLI = A.RUT AND X.CODCARR = A.CODCARPR AND X.ANO = 2025 AND X.CTADOC = 812) MONTO_BECA_MINESTERIAL,
    (SELECT TOP 1
        CASE
            WHEN X.SALDO > 0 AND X.FECVEN >= GETDATE() THEN 'VIGENTE'
            WHEN X.SALDO = 0 THEN 'CANCELADA'
            WHEN X.SALDO > 0 AND X.FECVEN < GETDATE() THEN 'MOROSO'
        END
     FROM UNIACC.DBO.MT_CTADOC X
     WHERE X.CODCLI = A.RUT AND X.CODCARR = A.CODCARPR AND X.ANO = 2025 AND X.CTADOC = 812
     ORDER BY X.FECDEUDA DESC) ESTADO_BECA_MINE,
    (SELECT SUM(X.SALDO)
     FROM UNIACC.DBO.MT_CTADOC X
     WHERE X.CODCLI = A.RUT AND X.CODCARR = A.CODCARPR AND X.SALDO > 0 AND X.FECVEN < GETDATE()) DEUDA_MOROSA,
    (SELECT TOP 1 X.Numero
     FROM UNIACC.DBO.MT_LVTA X, UNIACC.DBO.MT_CTADOC Z
     WHERE X.rut = B.CODCLI + '-' + B.DIG
       AND X.Carrera = A.CODCARPR
       AND (X.TIPODOCTO = 41 OR X.TIPODOCTO = 34)
       AND X.num_operacion = Z.NUM_OPERACION
       AND (Z.ITEM = 2 OR Z.ITEM = 100)
       AND Z.ANO = 2026
     ORDER BY X.monto DESC) NUM_BOL_FACT,
    (SELECT TOP 1 X.NUM_OPERACION
     FROM UNIACC.DBO.MT_CTADOC X
     WHERE X.CODCLI = A.RUT AND X.CODCARR = A.CODCARPR AND X.ANO = 2025 AND X.ITEM = 2) NUM_CONTRATO,
    (SELECT TOP 1
        CASE
            WHEN COUNT(X.codcli) > 1 AND X.Firmado = 'SI' THEN 'SI'
            WHEN COUNT(X.codcli) = 1 AND X.Firmado = 'SI' THEN 'SI'
            WHEN COUNT(X.codcli) > 1 AND X.Firmado IN ('NO') THEN 'NO'
            ELSE 'NO'
        END
     FROM UNIACC.DBO.MT_FIRMA_DOC X
     WHERE X.codcli = A.RUT AND X.ano = 2026
     GROUP BY X.codcli, X.Firmado) ESTADO_FIRMA,
    B.FONOACT,
    B.CELULARACT,
    B.MAIL,
    B.MAIL_INST,
    (SELECT TOP 1 X.CAJA
     FROM UNIACC.DBO.MT_CTADOC X
     WHERE X.CODCLI = A.RUT AND X.CODCARR = A.CODCARPR AND X.ANO = 2026 AND X.ITEM = 2
     ORDER BY X.FECREG DESC) CAJA,
    (SELECT TOP 1 Y.pe_nombrecompleto
     FROM UNIACC.DBO.MT_CTADOC X, UNIACC.DBO.CA_USUARIOS Z, UNIACC.DBO.tg_personas Y
     WHERE X.CODCLI = A.RUT AND X.CODCARR = A.CODCARPR
       AND X.ANO = 2026 AND X.ITEM = 2
       AND X.USUARIO = Z.id_usuario
       AND Z.id_persona = Y.id_persona
     ORDER BY X.FECREG DESC) USUARIO_MAT,
    NULL USUARIO_APRUEBA_POST,
    P.RUT RUT_APOD,
    P.DIG DV_APOD,
    P.NOMBRE NOMBRE_APOD,
    P.PATERNO AP_PATERNO_APOD,
    P.MATERNO AP_MATERNO_APOD,
    P.CELULAR TELEFONO_APOD,
    P.MAIL MAIL_APOD,
    (SELECT SUM(X.MONTO)
     FROM UNIACC.DBO.MT_CTAPAG X
     WHERE X.CODCLI = A.RUT
       AND X.CODCARR = A.CODCARPR
       AND X.FECREG >= DATEFROMPARTS(2023, 9, 27)
       AND X.CTAPAG = 386) PAGODOC386,
    GETDATE() FECHA_ACTUALIZACION
FROM UNIACC.DBO.MT_ALUMNO A
INNER JOIN UNIACC.DBO.MT_CLIENT B ON A.RUT = B.CODCLI
INNER JOIN UNIACC.DBO.MT_CARRER C ON A.CODCARPR = C.CODCARR
INNER JOIN UNIACC.DBO.MT_TIPOCARR D ON C.TIPOCARR = D.TIPOCARR
INNER JOIN UNIACC.DBO.RA_FACULTAD E ON C.CODFAC = E.CODFAC
INNER JOIN UNIACC.DBO.RA_TIPOSITU F ON A.TIPOSITU = F.CODIGO
INNER JOIN UNIACC.DBO.MT_DOCITEM G
    ON A.RUT = G.CODCLI
   AND A.CODCARPR = G.CODCARR
   AND A.CODSEDE = G.SEDE
INNER JOIN UNIACC.DBO.MT_ITEM H ON G.ITEM = H.CODITEM
INNER JOIN UNIACC.DBO.MT_APODER P ON B.CODAPOD = P.CODAPOD
INNER JOIN UNIACC.DBO.MT_CATALUMNO U ON B.CATEGORIA = U.CODCAT
WHERE A.ANO_MAT = 2026
  AND G.ITEM = 2
  AND G.ANO = 2026
  AND A.FEC_MAT >= DATEFROMPARTS(2025, 10, 13)
and A.RUT = 17634486;