SELECT C.MAIL_INST,dbo.DECRYPT(U.US_PASSWORD) AS CLAVE
FROM MT_ALUMNO A
INNER JOIN MT_CLIENT C
ON A.RUT=C.CODCLI
INNER JOIN MT_CARRER R
ON A.CODCARPR=R.CODCARR
INNER JOIN MT_TIPOMAT T
ON R.TIPOMAT=T.TIPOMAT
INNER JOIN RA_PESTUD P
ON A.CODPESTUD=P.CODPESTUD
INNER JOIN CA_USUARIOS U
ON U.US_CONSUSER=A.RUT+C.DIG

WHERE A.ESTACAD='VIGENTE' AND A.PERIODOS=1 AND R.TIPOCARR=1 AND
CONVERT(VARCHAR(4),A.ANO_MAT)+'-'+CONVERT(VARCHAR(1),A.PERIODO_MAT)<>'2026-2'    --CONVERT(VARCHAR(4),T.ANO_MAT)+'-'+CONVERT(VARCHAR(1),T.PERIODO_MAT)