SELECT
          INT.*,
          C1.NOMBRE_C as NOMBRE_C,
          C2.NOMBRE_C as NOMBRE_C2,
          C3.NOMBRE_C as NOMBRE_C3,
          C4.NOMBRE_C as NOMBRE_C4,
          C5.NOMBRE_C as NOMBRE_C5,
          (SELECT
            PC.CODCARR,
            PC.ESTADO,
            PC.FECREG,
            PC.FECMOD,
            PC.PRIORIDAD,
            PC.JORNADA,
            PC.MATRICULADO,
            CARR.NOMBRE_C as NOMBRE_CARRERA
           FROM MT_POSCAR PC
           LEFT JOIN MT_CARRER CARR ON PC.CODCARR = CARR.CODCARR
           WHERE PC.CODPOSTUL = INT.CODINT
             AND PC.ANO = 2026
           FOR JSON PATH
          ) as estados_json,
          ISNULL((SELECT 'SI' FROM MT_ALUMNO X WHERE X.RUT=INT.RUT AND (X.CODCARPR=INT.CARRINT1 OR X.CODCARPR=INT.CARRINT2 OR X.CODCARPR=INT.CARRINT3 OR
          X.CODCARPR=INT.CARRINT4 OR X.CODCARPR=INT.CARRINT5) AND X.ESTACAD='VIGENTE' AND X.ANO_MAT=2025),'NO') AS ES_VIGENTE
        FROM MT_INTERE INT
        LEFT JOIN MT_CARRER C1 ON INT.CARRINT1 = C1.CODCARR
        LEFT JOIN MT_CARRER C2 ON INT.CARRINT2 = C2.CODCARR
        LEFT JOIN MT_CARRER C3 ON INT.CARRINT3 = C3.CODCARR
        LEFT JOIN MT_CARRER C4 ON INT.CARRINT4 = C4.CODCARR
        LEFT JOIN MT_CARRER C5 ON INT.CARRINT5 = C5.CODCARR
        WHERE INT.ANO=2026 AND INT.POSTULACION='SI' AND INT.FECREG >= '2025-08-01'
        ORDER BY INT.FECREG DESC